@include("layout.components.frontend.header")
@include("layout.components.frontend.hero")
@include("layout.components.frontend.about")
@include("layout.components.frontend.portfolio")
@include("layout.components.frontend.contact")
@include("layout.components.frontend.footer")